# Generated by Django 4.2.20 on 2026-02-13 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('size', models.DecimalField(decimal_places=2, max_digits=5)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HazardPictogram',
            fields=[
                ('gh_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('pictogram', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='HazardStatement',
            fields=[
                ('hazard_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('statements', models.TextField()),
                ('hazard_class', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('signal_word', models.CharField(max_length=10)),
                ('pictograms', models.ManyToManyField(to='store.hazardpictogram')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=100)),
                ('is_hidden', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LocationAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PrecautionaryStatement',
            fields=[
                ('precautionary_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('statement', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.department')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.role')),
            ],
        ),
        migrations.CreateModel(
            name='StatementPictogram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gh_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.hazardpictogram')),
                ('h_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.hazardstatement')),
            ],
        ),
        migrations.CreateModel(
            name='RolePermissions',
            fields=[
                ('permission', models.TextField(primary_key=True, serialize=False)),
                ('has_perm', models.BooleanField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.location')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.role')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('table', models.CharField(max_length=100, null=True)),
                ('key1', models.CharField(max_length=10, null=True)),
                ('key2', models.CharField(max_length=10, null=True)),
                ('action', models.TextField(null=True)),
                ('old_value', models.TextField(null=True)),
                ('new_value', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('notes', models.TextField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.user')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='attributes',
            field=models.ManyToManyField(to='store.locationattribute'),
        ),
        migrations.AddField(
            model_name='location',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.department'),
        ),
        migrations.AddField(
            model_name='location',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.location'),
        ),
        migrations.AddField(
            model_name='hazardstatement',
            name='precautionary_statements',
            field=models.ManyToManyField(to='store.precautionarystatement'),
        ),
        migrations.CreateModel(
            name='HazardPrecaution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.hazardstatement')),
                ('p_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.precautionarystatement')),
            ],
        ),
        migrations.CreateModel(
            name='ContainerHazards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.container')),
                ('h_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.hazardstatement')),
            ],
        ),
        migrations.CreateModel(
            name='ContainerChemicals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chemical_cas', models.CharField(max_length=12)),
                ('pubchem_cid', models.IntegerField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('preferred_unit', models.CharField(max_length=10)),
                ('state_of_matter', models.CharField(max_length=10)),
                ('manufacturer', models.CharField(max_length=100)),
                ('catalog_number', models.CharField(max_length=50)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.container')),
            ],
        ),
        migrations.AddField(
            model_name='container',
            name='hazards',
            field=models.ManyToManyField(blank=True, through='store.ContainerHazards', to='store.hazardstatement'),
        ),
        migrations.AddField(
            model_name='container',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.location'),
        ),
    ]
