# Generated by Django 4.2.19 on 2025-03-12 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Container",
            fields=[
                ("container_id", models.AutoField(primary_key=True, serialize=False)),
                ("product_name", models.CharField(max_length=100)),
                ("size", models.DecimalField(decimal_places=2, max_digits=5)),
                ("notes", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                ("department_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="HazardPictogram",
            fields=[
                ("pictogram_id", models.AutoField(primary_key=True, serialize=False)),
                ("image", models.ImageField(upload_to="")),
                ("description", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="LocationAttribute",
            fields=[
                ("attribute_id", models.AutoField(primary_key=True, serialize=False)),
                ("value", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="PrecautionaryStatement",
            fields=[
                (
                    "precautionary_code",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("statement", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                ("location_id", models.AutoField(primary_key=True, serialize=False)),
                ("level", models.IntegerField()),
                ("name", models.CharField(max_length=100)),
                ("is_hidden", models.BooleanField(default=False)),
                ("attributes", models.ManyToManyField(to="store.locationattribute")),
                (
                    "department",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="store.department",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="store.location"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HazardStatement",
            fields=[
                (
                    "hazard_code",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("statements", models.TextField()),
                ("hazard_class", models.CharField(max_length=50)),
                ("category", models.CharField(max_length=50)),
                ("signal_word", models.CharField(max_length=10)),
                ("pictograms", models.ManyToManyField(to="store.hazardpictogram")),
                (
                    "precautionary_statements",
                    models.ManyToManyField(to="store.precautionarystatement"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContainerChemicals",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chemical_cas", models.CharField(max_length=12)),
                ("pubchem_cid", models.IntegerField()),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=5)),
                ("preferred_unit", models.CharField(max_length=10)),
                ("state_of_matter", models.CharField(max_length=10)),
                ("manufacturer", models.CharField(max_length=100)),
                ("catalog_number", models.CharField(max_length=50)),
                (
                    "container",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.container",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="container",
            name="hazards",
            field=models.ManyToManyField(blank=True, to="store.hazardstatement"),
        ),
        migrations.AddField(
            model_name="container",
            name="location",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="store.location",
            ),
        ),
    ]
