# Generated by Django 4.2.19 on 2025-03-29 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_alter_location_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="level",
            field=models.IntegerField(null=True),
        ),
    ]
