# Generated by Django 4.2.20 on 2025-04-01 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('old_value', models.CharField(max_length=100, null=True)),
                ('new_value', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=500)),
                ('notes', models.CharField(max_length=500)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.user')),
            ],
        ),
    ]
