# Generated by Django 4.2.20 on 2025-04-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='log',
            name='new_value',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='notes',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='log',
            name='old_value',
            field=models.TextField(null=True),
        ),
    ]
