# Generated by Django 4.2.24 on 2025-09-21 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_log_description_alter_log_new_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='log',
            name='action',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='key1',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='key2',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='table',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='log',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='StatementPictogram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gh_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.hazardpictogram')),
                ('h_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.hazardstatement')),
            ],
        ),
        migrations.CreateModel(
            name='RolePermissions',
            fields=[
                ('permission', models.TextField(primary_key=True, serialize=False)),
                ('has_perm', models.BooleanField()),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.location')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.role')),
            ],
        ),
        migrations.CreateModel(
            name='HazardPrecaution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.hazardstatement')),
                ('p_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.precautionarystatement')),
            ],
        ),
        migrations.CreateModel(
            name='ContainerHazards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.container')),
                ('h_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.hazardstatement')),
            ],
        ),
    ]
