# Generated by Django 4.2.24 on 2025-09-22 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_role_log_action_log_key1_log_key2_log_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hazardpictogram',
            name='image',
        ),
        migrations.AddField(
            model_name='hazardpictogram',
            name='pictogram',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
