# Generated by Django 4.2.24 on 2025-10-09 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_hazardpictogram_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='role_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.role'),
            preserve_default=False,
        ),
    ]
