[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "chemstore"
version = "0.1.0"
description = "Chem Store is a chemical tracking website that allows easy navigation and organization of inventory. "
requires-python = ">=3.9, <3.10"
dependencies = [
    "django~=4.2.19",
    "django-bootstrap5==25.1",
    "fontawesomefree==6.6.0",
    "pillow~=11.1",
    "python-dotenv~=1.0.1",
    "servestatic==3.0.1",
    "uvicorn[standard]>=0.34.0",
]

[project.optional-dependencies]
deploy = [
    "gunicorn>=23.0.0",
    "mysqlclient>=2.2.7",
    "uvicorn-worker>=0.3.0",
]

[project.scripts]
dev = "chemstore.run:rundev"
